swagger: '2.0'
info:
  title: lookup-file
  x-ibm-name: lookup-file
  version: 1.0.0
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - gatewayscript:
          version: 2.0.0
          title: gatewayscript
          source: >-
            var fs = require('fs');


            fs.readFile("local:///lookup_files/lookup_file_config.json",
            function(error,data) {
                if(error) {
                    // Handle error.
                } else {
                    
                    //data is the content in local:///lookup_files/lookup_file_config.json
                    var vLookup_file = JSON.parse(data);
                    
                    //Get the current catalog during runtime.
                    var vCurrentCatalog = context.get('api.catalog.name');
                    
                    //Lookup the port configuration from the config file.
                    var vPort = vLookup_file[context.get('api.catalog.name')].port
                    
                    context.message.body.write(vPort);
                }
            }

            );
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
basePath: /lookup-property-config
paths:
  /:
    get:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    put:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    post:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    delete:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    head:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    patch:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
schemes:
  - https
